=== BiancaAlexandra/Dealer-Auto/DealerAutoOrbisorBiancaAlexandra.dtd
<!ELEMENT dealer_auto (comanda*)>

<!ELEMENT comanda (masina+, date_cumparator, dealer, accesibilitate_masina, statusul_masinii?, date_vanzator, date_autovehicul, data_semnarii, suma_de_plata, factura)>
<!ELEMENT accesibilitate_masina (#PCDATA)>
<!ELEMENT statusul_masinii (#PCDATA)>
<!ELEMENT data_semnarii (#PCDATA)>

<!ELEMENT masina (specificatii_tehnice)>

<!ELEMENT specificatii_tehnice (marca, tip, date_identificare, an_fabricatie, capacitate_cilindrica, putere, tip_combustibil, norma_de_poluare, culoare, viteza_maxima, tractiune, transmisie)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT an_fabricatie (#PCDATA)>
<!ELEMENT capacitate_cilindrica (#PCDATA)>
<!ELEMENT putere (#PCDATA)>
<!ELEMENT tip_combustibil (#PCDATA)>
<!ELEMENT norma_de_poluare (#PCDATA)>
<!ELEMENT culoare (#PCDATA)>
<!ELEMENT viteza_maxima (#PCDATA)>
<!ELEMENT tractiune (#PCDATA)>
<!ELEMENT transmisie (#PCDATA)>

<!ELEMENT tip (denumire_comerciala, varianta, versiune)>
<!ELEMENT denumire_comerciala (#PCDATA)>
<!ELEMENT varianta (#PCDATA)>
<!ELEMENT versiune (#PCDATA)>

<!ELEMENT date_identificare (serie_sasiu, serie_motor)>
<!ELEMENT serie_sasiu (#PCDATA)>
<!ELEMENT serie_motor (#PCDATA)>

<!ELEMENT date_cumparator (nume, prenume, adresa, nr_telefon, adresa_mail, cnp, serie_CI, nr_CI)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>
<!ELEMENT nr_telefon (#PCDATA)>
<!ELEMENT adresa_mail (#PCDATA)>
<!ELEMENT cnp (#PCDATA)>
<!ELEMENT serie_CI (#PCDATA)>
<!ELEMENT nr_CI (#PCDATA)>

<!ELEMENT dealer (nr_telefon+, adresa_mail)>

<!ELEMENT date_vanzator (localitate, consilier_de_vanzari, judet_sector, nr_telefon)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT consilier_de_vanzari (#PCDATA)>
<!ELEMENT judet_sector (#PCDATA)>

<!ELEMENT date_autovehicul (termen_de_livrare, denumire_model, cod_culoare_exterior, an_fabricatie, nr_km)>
<!ELEMENT termen_de_livrare (#PCDATA)>
<!ELEMENT denumire_model (#PCDATA)>
<!ELEMENT cod_culoare_exterior (#PCDATA)>
<!ELEMENT nr_km (#PCDATA)>

<!ELEMENT suma_de_plata (pret_lista_unitar, discount*, pret_unitar_de_vanzare)>
<!ELEMENT pret_lista_unitar (#PCDATA)>
<!ELEMENT pret_unitar_de_vanzare (#PCDATA)>
<!ELEMENT discount (valoare)>
<!ELEMENT valoare (#PCDATA)>

<!ELEMENT factura (client, adresa_client, denumire_produs, cantitate, total_de_plata)>
<!ELEMENT client (#PCDATA)>
<!ELEMENT adresa_client (#PCDATA)>
<!ELEMENT denumire_produs (#PCDATA)>
<!ELEMENT cantitate (#PCDATA)>
<!ELEMENT total_de_plata (#PCDATA)>

<!ATTLIST comanda numar CDATA #REQUIRED>
<!ATTLIST adresa strada CDATA #REQUIRED>
<!ATTLIST adresa numar CDATA #REQUIRED>
<!ATTLIST adresa oras CDATA #REQUIRED>
<!ATTLIST dealer nume CDATA #REQUIRED>
<!ATTLIST dealer prenume CDATA #REQUIRED>
<!ATTLIST date_vanzator denumire CDATA #REQUIRED>
<!ATTLIST discount denumire CDATA #REQUIRED>
<!ATTLIST factura serie CDATA #REQUIRED>
<!ATTLIST factura numar CDATA #REQUIRED>
<!ATTLIST factura data CDATA #REQUIRED>

=== BiancaAlexandra/Dealer-Auto/DealerAutoOrbisorBiancaAlexandra.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="DealerAutoOrbisorBiancaAlexandra.xsl"?>
<!-- Orbisor Bianca-Alexandra, 343A3 -->

<!-- DTD -->
<!DOCTYPE dealer_auto SYSTEM "DealerAutoOrbisorBiancaAlexandra.dtd">

<!-- XMLShema -->
<dealer_auto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XmlSchemaDealer.xsd">


	<comanda numar="1">
		<masina>
			<specificatii_tehnice>
				<marca>Toyota</marca>
				<tip>
					<denumire_comerciala>Yaris</denumire_comerciala>
					<varianta>NBP21(MH)</varianta>
					<versiune>NBP211L-CHFNBW(1R)</versiune>
				</tip>
				<date_identificare>
					<serie_sasiu>ABCDE4G111B123456</serie_sasiu>
					<serie_motor>2NR-FKE</serie_motor>
				</date_identificare>
				<an_fabricatie>2019</an_fabricatie>
				<capacitate_cilindrica>1496</capacitate_cilindrica>
				<putere>82</putere>
				<tip_combustibil>benzina</tip_combustibil>
				<norma_de_poluare>6</norma_de_poluare>
				<culoare>alb</culoare>
				<viteza_maxima>175</viteza_maxima>
				<tractiune>fata</tractiune>
				<transmisie>manuala</transmisie>
			</specificatii_tehnice>
		</masina>

		<date_cumparator>
			<nume>Ion</nume>
			<prenume>Maria</prenume>
			<adresa strada="Unirii" numar="7" oras="Bucuresti"></adresa>
			<nr_telefon>0758954823</nr_telefon>
			<adresa_mail>ion.maria@yahoo.com</adresa_mail>
			<cnp>2970221475584</cnp>
			<serie_CI>RR</serie_CI>
			<nr_CI>444444</nr_CI>
		</date_cumparator>

		<dealer nume="Ionescu" prenume="Ion">
			<nr_telefon>0748775566</nr_telefon>
			<adresa_mail>ionescu.ion@gmail.com</adresa_mail>
		</dealer>

		<accesibilitate_masina>stoc</accesibilitate_masina>
		<statusul_masinii>asteptare</statusul_masinii>

		<date_vanzator denumire="Toyo Motor Centre">
			<localitate>Bucuresti</localitate>
			<consilier_de_vanzari>Ion Ionescu</consilier_de_vanzari>
			<judet_sector>3</judet_sector>
			<nr_telefon>0788885513</nr_telefon>
		</date_vanzator>

		<date_autovehicul>
			<termen_de_livrare>20</termen_de_livrare>
			<denumire_model>Yaris</denumire_model>
			<cod_culoare_exterior>040</cod_culoare_exterior>
			<an_fabricatie>2019</an_fabricatie>
			<nr_km>0</nr_km>
		</date_autovehicul>

		<data_semnarii>13.12.2019</data_semnarii>

		<suma_de_plata>
			<pret_lista_unitar>15714</pret_lista_unitar>
			<discount denumire="promotie">
				<valoare>2314</valoare>
			</discount>
			<discount denumire="reducere">
				<valoare>400</valoare>
			</discount>
			<pret_unitar_de_vanzare>13000</pret_unitar_de_vanzare>
		</suma_de_plata>

		<factura serie="ABC21" numar="212" data="10.01.2020">
			<client>Ion Maria</client>
			<adresa_client>Dristor</adresa_client>
			<denumire_produs>Yaris</denumire_produs>
			<cantitate>1</cantitate>
			<total_de_plata>13000</total_de_plata>
		</factura>
	</comanda>

	<comanda numar="2">
		<masina>
			<specificatii_tehnice>
				<marca>Toyota</marca>
				<tip>
					<denumire_comerciala>Corolla</denumire_comerciala>
					<varianta>NBP20(MH)</varianta>
					<versiune>NBP201L-CHFNBW(1R)</versiune>
				</tip>
				<date_identificare>
					<serie_sasiu>ABCDE4G111B123455</serie_sasiu>
					<serie_motor>8NR-FTS</serie_motor>
				</date_identificare>
				<an_fabricatie>2017</an_fabricatie>
				<capacitate_cilindrica>1197</capacitate_cilindrica>
				<putere>85</putere>
				<tip_combustibil>benzina</tip_combustibil>
				<norma_de_poluare>6</norma_de_poluare>
				<culoare>albastru</culoare>
				<viteza_maxima>195</viteza_maxima>
				<tractiune>fata</tractiune>
				<transmisie>automata</transmisie>
			</specificatii_tehnice>
		</masina>

		<date_cumparator>
			<nume>Ghita</nume>
			<prenume>Mihai</prenume>
			<adresa strada="Militari" numar="3" oras="Bucuresti"></adresa>
			<nr_telefon>0725658545</nr_telefon>
			<adresa_mail>ghita.mihai@yahoo.com</adresa_mail>
			<cnp>1970221471111</cnp>
			<serie_CI>RA</serie_CI>
			<nr_CI>111111</nr_CI>
		</date_cumparator>

		<dealer nume="Oncescu" prenume="Laurentiu">
			<nr_telefon>0744115787</nr_telefon>
			<adresa_mail>oncescu.laurentiu@gmail.com</adresa_mail>
		</dealer>

		<accesibilitate_masina>stoc</accesibilitate_masina>
		<statusul_masinii>asteptare</statusul_masinii>

		<date_vanzator denumire="Toyo Motor Centre">
			<localitate>Bucuresti</localitate>
			<consilier_de_vanzari>Laurentiu Oncescu</consilier_de_vanzari>
			<judet_sector>3</judet_sector>
			<nr_telefon>0788885513</nr_telefon>
		</date_vanzator>

		<date_autovehicul>
			<termen_de_livrare>30</termen_de_livrare>
			<denumire_model>Corolla</denumire_model>
			<cod_culoare_exterior>059</cod_culoare_exterior>
			<an_fabricatie>2017</an_fabricatie>
			<nr_km>75000</nr_km>
		</date_autovehicul>

		<data_semnarii>21.02.2020</data_semnarii>

		<suma_de_plata>
			<pret_lista_unitar>16500</pret_lista_unitar>
			<pret_unitar_de_vanzare>16500</pret_unitar_de_vanzare>
		</suma_de_plata>

		<factura serie="ABC22" numar="221" data="21.02.2020">
			<client>Ghita Mihai</client>
			<adresa_client>Berceni</adresa_client>
			<denumire_produs>Corolla</denumire_produs>
			<cantitate>1</cantitate>
			<total_de_plata>16500</total_de_plata>
		</factura>
	</comanda>

	<comanda numar="3">
		<masina>
			<specificatii_tehnice>
				<marca>Toyota</marca>
				<tip>
					<denumire_comerciala>Aygo</denumire_comerciala>
					<varianta>NAA21(MH)</varianta>
					<versiune>NAA211L-CHFNBW(1R)</versiune>
				</tip>
				<date_identificare>
					<serie_sasiu>ABCDE4G111B123401</serie_sasiu>
					<serie_motor>1KR-FE</serie_motor>
				</date_identificare>
				<an_fabricatie>2020</an_fabricatie>
				<capacitate_cilindrica>998</capacitate_cilindrica>
				<putere>72</putere>
				<tip_combustibil>benzina</tip_combustibil>
				<norma_de_poluare>6</norma_de_poluare>
				<culoare>negru</culoare>
				<viteza_maxima>160</viteza_maxima>
				<tractiune>fata</tractiune>
				<transmisie>manuala</transmisie>
			</specificatii_tehnice>
		</masina>

		<date_cumparator>
			<nume>Marcelescu</nume>
			<prenume>Marcel</prenume>
			<adresa strada="Unirii" numar="13" oras="Bucuresti"></adresa>
			<nr_telefon>0758621458</nr_telefon>
			<adresa_mail>marcelescu.marcel@yahoo.com</adresa_mail>
			<cnp>1970221472525</cnp>
			<serie_CI>RB</serie_CI>
			<nr_CI>999888</nr_CI>
		</date_cumparator>

		<dealer nume="Ionescu" prenume="Ion">
			<nr_telefon>0748775566</nr_telefon>
			<adresa_mail>ionescu.ion@gmail.com</adresa_mail>
		</dealer>

		<accesibilitate_masina>comanda</accesibilitate_masina>
		<statusul_masinii>productie</statusul_masinii>

		<date_vanzator denumire="Toyo Motor Centre">
			<localitate>Bucuresti</localitate>
			<consilier_de_vanzari>Ionescu Ion</consilier_de_vanzari>
			<judet_sector>3</judet_sector>
			<nr_telefon>0788885513</nr_telefon>
		</date_vanzator>

		<date_autovehicul>
			<termen_de_livrare>35</termen_de_livrare>
			<denumire_model>Aygo</denumire_model>
			<cod_culoare_exterior>080</cod_culoare_exterior>
			<an_fabricatie>2020</an_fabricatie>
			<nr_km>0</nr_km>
		</date_autovehicul>

		<data_semnarii>21.05.2020</data_semnarii>

		<suma_de_plata>
			<pret_lista_unitar>9637</pret_lista_unitar>
			<discount denumire="promotie">
				<valoare>637</valoare>
			</discount>
			<pret_unitar_de_vanzare>9000</pret_unitar_de_vanzare>
		</suma_de_plata>

		<factura serie="AAA21" numar="221" data="10.05.2020">
			<client>Marcelescu Marcel</client>
			<adresa_client>Pipera</adresa_client>
			<denumire_produs>Aygo</denumire_produs>
			<cantitate>1</cantitate>
			<total_de_plata>9000</total_de_plata>
		</factura>
	</comanda>
</dealer_auto>
